### ISSUE TITLE
Need help with `out of bounds memory access` issue

### ISSUE THREAD

**Issue by FiveMovesAhead** [wasmi-labs/wasmi#1133]
**Disclaimer:** This is likely a case of me not fully understanding how to configure `wasmi`.

[I have put together a simple repo to replicate the issue](https://github.com/FiveMovesAhead/wasmi_mem_issue)

1. I am setting memory limit of 1GB:
  ```
  let limits = StoreLimitsBuilder::new()
              .memory_size(MAX_MEMORY)
              .memories(1)
              .trap_on_grow_failure(true)
              .build();
  ```

2. I am writing simple text data, incrementing by 1kb each time, to `memory`:
  ```
  let serialized_text =
              bincode::serialize(&"A".repeat(n * 1024)).expect("Failed to serialize");
  let memory = instance
      .get_memory(&store, "memory")
      .expect("Failed to find memory");
  memory.grow(&mut store, NUM_PAGES.into()).unwrap();
  memory
      .write(&mut store, 0, &(serialized_text.len() as u32).to_le_bytes())
      .expect("Failed to write to memory");
  memory
      .write(&mut store, 4, &serialized_text)
      .expect("Failed to write to memory");
  ```

3. The wasm is just deserializing that data:
  ```
  #[no_mangle]
  pub fn entry_point(ptr: *const u8) {
      let len: usize = unsafe { *(ptr as *const u32) } as usize;
      let data = unsafe { std::slice::from_raw_parts(ptr.add(4), len) };
      let text: String = bincode::deserialize(&data).expect("Failed to deserialize");
  }
  ```

4. Despite memory limits set to 1GB, an out of bounds memory access error occurs at 1033kb of data
```
...
Testing with 1031kb of data
Testing with 1032kb of data
Testing with 1033kb of data
thread 'main' panicked at app/src/main.rs:46:13:
Error occured during execution: out of bounds memory access
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Any help with this issue is highly appreciated

**Comment by Robbepop** [comment]
Hi @FiveMovesAhead , thank you for the bug report or for asking the question.

From what I see the `StoreLimits` usage indeed seems to be off in the provided code.

This is about this line of code:
https://github.com/FiveMovesAhead/wasmi_mem_issue/blob/main/app/src/main.rs#L18

Here the `Store` is initialized with `limits: StoreLimits` as its host data.

The actual API that you want to use to properly set the store's limits is this:
https://docs.rs/wasmi/0.35.0/wasmi/struct.Store.html#method.limiter

Then it all should work as expected. :)

**Comment by FiveMovesAhead** [comment]
Thanks for your fast response!

I have modified the code to include `store.limiter(..)` and have also adjusted the `memory.grow` as it now throws `OutOfBoundsGrowth` error:
```
let mut store = Store::new(&engine, limits);
store.limiter(|lim| lim);
...
memory.grow(&mut store, (NUM_PAGES - 100).into()).unwrap();
```

However, I am still running into the same `out of bounds memory access` error as before:
```
...
Testing with 1032kb of data
Testing with 1033kb of data
thread 'main' panicked at app/src/main.rs:47:13:
Error occured during execution: out of bounds memory access
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Is it somehow because linear memory is somehow not contiguous when accessed from inside the wasm module?

**Comment by FiveMovesAhead** [comment]
Digging into it more... the issue is coming from opcode `LoadOffset16Instr`.. 

Addresses stay within reasonable values for 1032kb of data
```
Testing with 1032kb of data
LoadOffset16Instr @ address 0
LoadOffset16Instr @ address 0
LoadOffset16Instr @ address 1057612
LoadOffset16Instr @ address 1057612
LoadOffset16Instr @ address 1057612
LoadOffset16Instr @ address 1057612
LoadOffset16Instr @ address 1057612
LoadOffset16Instr @ address 1057612
LoadOffset16Instr @ address 1057612
LoadOffset16Instr @ address 1057612
LoadOffset16Instr @ address 1057612
LoadOffset16Instr @ address 1057612
LoadOffset16Instr @ address 1057612
LoadOffset16Instr @ address 1114056
LoadOffset16Instr @ address 4390928
LoadOffset16Instr @ address 4390932
LoadOffset16Instr @ address 4390928
LoadOffset16Instr @ address 4390940
LoadOffset16Instr @ address 4390936
...
```

Addresses suddenly spike to a very high value for 1033kb of data:
```
Testing with 1033kb of data
LoadOffset16Instr @ address 0
LoadOffset16Instr @ address 0
LoadOffset16Instr @ address 1057564
LoadOffset16Instr @ address 1094795585
thread 'main' panicked at app/src/main.rs:47:13:
Error occured during execution: out of bounds memory access
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Robbepop** [comment]
> I have just tested with wasmtime instead of wasmi, and the same out of bounds memory access error occurs for 1033kb of data..

Thanks for testing this. This means that the issue is likely originating from the Wasm binary since both runtimes agree on the behavior.

Concerning your Rust source for the Wasm binary:

```rust
#[no_mangle]
pub fn entry_point(ptr: u32) {
    let len: usize = unsafe { *(ptr as *const u32) } as usize;
    let ptr = ptr as *const u8;
    let data = unsafe { std::slice::from_raw_parts(ptr.add(4), len) };
    let text: String = bincode::deserialize(&data).expect("Failed to deserialize");
}
```

Could you try to provide the slice length as `entry_point` parameter instead of via linear memory? Also it should be possible to provide `ptr` as pointer and be able to still use `u32` on the host side since you are compiling to `wasm32-unknown-unknown` target with guaranteed 32-bit pointers. Like so:

```rust
#[no_mangle]
pub fn entry_point(ptr: *mut u8, len: u32) {
    let data = unsafe { std::slice::from_raw_parts(ptr, len) };
    let _text: String = bincode::deserialize(data).expect("failed to deserialize");
}
```

**Comment by Robbepop** [comment]
Can you push your recent changes to the repo. Then I will clone it locally and debug it myself. It is kinda hard to debug remotely.

**Comment by FiveMovesAhead** [comment]
Just pushed. Thanks a lot. 

FYI, I got this tip from another developer:
```
You are corrupting the memory of the wasm module by overwriting it's stack and global data, which then results in the wasm module accessing an invalid address. If you want to pass a string to the linear memory, you will have to add a function to allocate memory to the wasm module and then call this function from the host to determine where to write the string.
```

Trying to figure out how to test his proposal. Any help would be highly appreciated

**Comment by Robbepop** [comment]
> You are corrupting the memory of the wasm module by overwriting it's stack and global data, which then results in the wasm module accessing an invalid address. If you want to pass a string to the linear memory, you will have to add a function to allocate memory to the wasm module and then call this function from the host to determine where to write the string.

Ah yes, I should have thought about that, too!

I have cloned the repo locally and fixed it for Wasmi:

Wasm Blob:

```rust
use core::slice;

/// Allocates a new boxed slice on the Wasm side and returns a raw pointer to it.
#[no_mangle]
pub fn init(len: u32) -> *mut u8 {
    Box::leak(vec![0x00_u8; len as usize].into_boxed_slice()).as_mut_ptr()
}

/// Deallocates the boxed slice allocated via [`init`].
///
/// The `len` must match the `len` given to [`init`].
#[no_mangle]
pub fn deinit(data: *mut u8, len: u32) {
    let len = len as usize;
    let vec = unsafe { Vec::from_raw_parts(data, len, len) };
    drop(vec)
}

/// Deserializes the `String` from the slice allocated via [`init`].
///
/// The `len` must match the `len` given to [`init`].
#[no_mangle]
pub fn deserialize(ptr: *mut u8, len: u32) {
    let data = unsafe { slice::from_raw_parts(ptr, len as usize) };
    let _text: String = bincode::deserialize(data).expect("failed to deserialize");
}
```

Wasmi App:

```rust
use wasmi::{Config, Engine, Linker, Module, Store, StoreLimitsBuilder};

const MAX_MEMORY: usize = 1 * 1024 * 1024 * 1024; // 1GB

fn main() {
    println!("Loading ./wasm_blob.wasm");
    let wasm = std::fs::read("./wasm_blob.wasm").expect("Failed to read wasm file");
    for n in 1030..2000 {
        println!("Testing with {}kb of data", n);
        let config = Config::default();
        let limits = StoreLimitsBuilder::new()
            .memory_size(MAX_MEMORY)
            .memories(1)
            .trap_on_grow_failure(true)
            .build();
        let engine = Engine::new(&config);
        let mut store = Store::new(&engine, limits);
        store.limiter(|lim| lim);
        let linker = Linker::new(&engine);
        let module =
            Module::new(store.engine(), &*wasm).expect("Wasmi: failed to instantiate module");
        let instance = &linker
            .instantiate(&mut store, &module)
            .expect("Wasmi: failed to instantiate linker")
            .start(&mut store)
            .expect("Wasmi: failed to start module");
        let serialized_text =
            bincode::serialize(&"A".repeat(n * 1024)).expect("Wasmi: failed to serialize");
        let memory = instance
            .get_memory(&store, "memory")
            .expect("Wasmi: failed to find `memory`");
        let init = instance
            .get_typed_func::<u32, u32>(&store, "init")
            .expect("Wasmi: failed to find `init` function");
        let deinit = instance
            .get_typed_func::<(u32, u32), ()>(&store, "deinit")
            .expect("Wasmi: failed to find `deinit` function");
        let deserialize = instance
            .get_typed_func::<(u32, u32), ()>(&store, "deserialize")
            .expect("Wasmi: failed to find `deserialize` function");
        let data_len: u32 = serialized_text.len() as u32;
        let data_ptr: u32 = init.call(&mut store, data_len).unwrap();
        memory
            .write(&mut store, data_ptr as usize, &serialized_text)
            .expect("Wasmi: failed to write serialized text to `memory`");
        deserialize.call(&mut store, (data_ptr, data_len)).unwrap();
        deinit.call(&mut store, (data_ptr, data_len)).unwrap();
    }
}
```

Outputs:

```
Running wasmi_app
Loading ./wasm_blob.wasm
Testing with 1030kb of data
Testing with 1031kb of data
Testing with 1032kb of data
Testing with 1033kb of data
Testing with 1034kb of data
Testing with 1035kb of data
Testing with 1036kb of data
Testing with 1037kb of data
Testing with 1038kb of data
Testing with 1039kb of data
Testing with 1040kb of data
Testing with 1041kb of data
Testing with 1042kb of data
etc..
```

**Comment by FiveMovesAhead** [comment]
perfect! Thank you so much
